### ISSUE TITLE
Switch to using setuptools_scm

### ISSUE THREAD

**Issue by blag** [jazzband/django-user-sessions#167]
Switch to using [`setuptools_scm`](https://pypi.org/project/setuptools-scm/) to handle versioning.

## Context

Context is [here.](https://github.com/jazzband/django-user-sessions/pull/166#pullrequestreview-1654878821)

**Comment by WhyNotHugo** [comment]
I'll switch to `pyproject.toml` before doing this.

Mostly, we can generate a file with the version via:


```toml
[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]

[tool.setuptools_scm]
write_to = "user_sessions/version.py"
version_scheme = "post-release"
```
